# Generated by Django 4.1.6 on 2023-02-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lname',
        ),
    ]
