# Generated by Django 4.1.6 on 2023-02-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_fname_member_name_remove_member_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='fname',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='lname',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
